Upgrade project to `>=3.10`: Deprecate 3.8 / 3.9; test against 3.13 / 3.14; `pre-commit autoupdate` + `pyupgrade`
Due to the https://results.pre-commit.ci/run/github/602434841/1767562414.bHoKHEk8SOKSdCCfiG_vow:

* We need to upgrade to at least 3.9 python (mypy)
* `pylint/checkers/variables.py:112: error: Pattern matching is only supported in Python 3.10 and greater  [syntax]`

... and because 3.9 is soon-to-be EOL _as of writing this_, let us deprecate this one too.

Additionally, adding `https://github.com/asottile/pyupgrade` will help with the transition

Signed-off-by: Stavros Ntentos <133706+stdedos@users.noreply.github.com>